/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotellerio;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author rithesh
 */
public class Update_Emp_Info extends javax.swing.JFrame {

    /**
     * Creates new form Update_Emp_Info
     */
    public Update_Emp_Info() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        field = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oldvalue = new javax.swing.JTextField();
        newvalue = new javax.swing.JTextField();
        oldname_err = new javax.swing.JLabel();
        newname_err = new javax.swing.JLabel();
        confirm_update = new javax.swing.JButton();
        cancel_08 = new javax.swing.JButton();
        reset_08 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        pass_err = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        empid_err = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Update Employee Details Here...");

        jLabel2.setText("Choose feild to be Updated");

        field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Age", "Address", "Phone", "Username", "Pssword" }));

        jLabel3.setText("Old Value");

        jLabel4.setText("New Value");

        oldvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldvalueActionPerformed(evt);
            }
        });

        confirm_update.setText("Confirm");
        confirm_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_updateActionPerformed(evt);
            }
        });

        cancel_08.setText("Cancel");
        cancel_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_08ActionPerformed(evt);
            }
        });

        reset_08.setText("Reset");
        reset_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_08ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotellerio/images/emp_update.png"))); // NOI18N

        jLabel7.setText("Repair Your Employee Here...");

        jLabel8.setText("Your Password");

        jLabel9.setText("Employee ID");

        emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_idActionPerformed(evt);
            }
        });
        emp_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emp_idKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cancel_08)
                                        .addGap(69, 69, 69)
                                        .addComponent(reset_08)
                                        .addGap(54, 54, 54)
                                        .addComponent(confirm_update))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(empid_err, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                            .addComponent(pass_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(newname_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(oldvalue)
                                            .addComponent(newvalue)
                                            .addComponent(oldname_err, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(password)
                                            .addComponent(emp_id, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                                .addGap(49, 49, 49)
                                .addComponent(jLabel6)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(oldvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oldname_err, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(newvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newname_err, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empid_err, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_err, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirm_update)
                    .addComponent(cancel_08)
                    .addComponent(reset_08))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void oldvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldvalueActionPerformed

    private void reset_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_08ActionPerformed
        // TODO add your handling code here:
        oldvalue.setText("");
        newvalue.setText("");
        password.setText("");
        oldname_err.setText("");
        newname_err.setText("");
        pass_err.setText("");
        empid_err.setText("");
        emp_id.setText("");
    }//GEN-LAST:event_reset_08ActionPerformed

    private void cancel_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_08ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Employee_Section().setVisible(true);
    }//GEN-LAST:event_cancel_08ActionPerformed

    private void confirm_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_updateActionPerformed
        // TODO add your handling code here:
        if(oldvalue.getText().trim().isEmpty() && newvalue.getText().trim().isEmpty() && password.getText().trim().isEmpty() && emp_id.getText().trim().isEmpty())
        {
            oldname_err.setText("*This field is required");
            oldname_err.setForeground(Color.red);
            newname_err.setText("*This field is required");
            newname_err.setForeground(Color.red);
            pass_err.setText("*This field is required");
            pass_err.setForeground(Color.red);
            empid_err.setText("*This field is required");
            empid_err.setForeground(Color.red);
        }
        else if(oldvalue.getText().trim().isEmpty())
        {
            oldname_err.setText("*This field is required");
            oldname_err.setForeground(Color.red);
            newname_err.setText("");
            pass_err.setText("");
            empid_err.setText("");
        }
        else if(newvalue.getText().trim().isEmpty())
        {
            oldname_err.setText("");
            newname_err.setForeground(Color.red);
            newname_err.setText("*This field is required");
            pass_err.setText("");
            empid_err.setText("");
        }
         else if(password.getText().trim().isEmpty())
        {
            oldname_err.setText("");
            pass_err.setForeground(Color.red);
            newname_err.setText("");
            pass_err.setText("*This field is required");
            empid_err.setText("");
        }
        else if(emp_id.getText().trim().isEmpty())
        {
            oldname_err.setText("");
            empid_err.setForeground(Color.red);
            newname_err.setText("");
            pass_err.setText("");
            empid_err.setText("*This field is required");
        }
            
        else{
            try {
                Connection con1 = DBConnect.connect();
                int customer_id = Integer.valueOf(this.emp_id.getText());
            String sqlc="select Name from employee_details where ID=?";
            PreparedStatement psc = con1.prepareStatement(sqlc);
            psc.setInt(1, customer_id);
            ResultSet rsc = psc.executeQuery();
            if(rsc.next()){
                int x = JOptionPane.YES_NO_OPTION;
        int y = JOptionPane.showConfirmDialog(this, "Confirm with above details?", "Title on Box", x);
        if(y == 0) 
        {
            try{
               Connection conn = DBConnect.connect();
                    String sql="select username_01 from admin_auth where password_01=?";
                    PreparedStatement pst=conn.prepareStatement(sql);
                    pst.setString(1,String.valueOf(password.getPassword()));
                    ResultSet rs = pst.executeQuery();
                    if(rs.next())
                    {
                        System.out.println(rs.getString(1));
                        String fields = String.valueOf(field.getSelectedItem());
                        String sql1 = "update employee_details set "+fields+" =? where ID=?";
                        System.out.println(fields);
                        PreparedStatement pst1 = conn.prepareStatement(sql1);
                        pst1.setString(1,String.valueOf(newvalue.getText()));
                        pst1.setInt(2,Integer.valueOf(emp_id.getText()));
                        pst1.executeUpdate();
                        System.out.println("fields Updated");
                        conn.close();
                    }
                
           }
       catch(NumberFormatException | SQLException e) {
           System.out.println(e);
                      }        } 
        else {
            this.setVisible(false);
            new Employee_Section().setVisible(true);
        }

            } 
            else
            {
                 JOptionPane.showMessageDialog(null, "There is no customer with given ID.Please Enter details Again","Display Message",JOptionPane.INFORMATION_MESSAGE);

            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e,"Display Message",JOptionPane.INFORMATION_MESSAGE);
            
            }
        
        }
    }//GEN-LAST:event_confirm_updateActionPerformed

    private void emp_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_idKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) ||(c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_emp_idKeyTyped

    private void emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Emp_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_08;
    private javax.swing.JButton confirm_update;
    private javax.swing.JTextField emp_id;
    private javax.swing.JLabel empid_err;
    private javax.swing.JComboBox<String> field;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel newname_err;
    private javax.swing.JTextField newvalue;
    private javax.swing.JLabel oldname_err;
    private javax.swing.JTextField oldvalue;
    private javax.swing.JLabel pass_err;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset_08;
    // End of variables declaration//GEN-END:variables
}
